### ISSUE TITLE
加载插件时发生错误: No module named 'tkinter'

### ISSUE THREAD

**Issue by Agnes4m** [baiqwerdvd/ArknightsUID#3]
更新了最新版本，尝试了poetry run pip install tkinter，得到没有这个pypi包
## 报错
```
2024-06-13 17:28:56.269 | ERROR    | gsuid_core.server:load_plugins:149 - 加载插件时发生错误: No module named 'tkinter'
Traceback (most recent call last):

  File "/home/ubuntu/bot/gsuid_core1/gsuid_core/core.py", line 15, in <module>
    from gsuid_core.gss import gss  # noqa: E402

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/home/ubuntu/bot/gsuid_core1/gsuid_core/gss.py", line 12, in <module>
    gss.load_plugins()
    │   └ <function GsServer.load_plugins at 0x7f12bb22ba30>
    └ <gsuid_core.server.GsServer object at 0x7f12bd9f6740>

> File "/home/ubuntu/bot/gsuid_core1/gsuid_core/server.py", line 121, in load_plugins
    self.load_dir_plugins(path, True)
    │    │                └ PosixPath('/home/ubuntu/bot/gsuid_core1/gsuid_core/plugins/ArknightsUID/ArknightsUID')
    │    └ <function GsServer.load_dir_plugins at 0x7f12bb22bac0>
    └ <gsuid_core.server.GsServer object at 0x7f12bd9f6740>

  File "/home/ubuntu/bot/gsuid_core1/gsuid_core/server.py", line 172, in load_dir_plugins
    importlib.import_module(f'{_p}')
    │         └ <function import_module at 0x7f12bdf55ab0>
    └ <module 'importlib' from '/usr/lib/python3.10/importlib/__init__.py'>

  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'plugins.ArknightsUID.ArknightsUID.arknightsuid_resource'
           │          └ <function _gcd_import at 0x7f12be95f400>
           └ <module '_frozen_importlib' (frozen)>
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/home/ubuntu/bot/gsuid_core1/gsuid_core/plugins/ArknightsUID/ArknightsUID/arknightsuid_resource/__init__.py", line 4, in <module>
    from gsuid_core.plugins.ArknightsUID.ArknightsUID.utils.resource.download_all_resource import (

  File "/home/ubuntu/bot/gsuid_core1/gsuid_core/plugins/ArknightsUID/ArknightsUID/utils/resource/download_all_resource.py", line 3, in <module>
    from .download_from_cos import download_all_file_from_cos

  File "/home/ubuntu/bot/gsuid_core1/gsuid_core/plugins/ArknightsUID/ArknightsUID/utils/resource/download_from_cos.py", line 3, in <module>
    from .RESOURCE_PATH import (

  File "/home/ubuntu/bot/gsuid_core1/gsuid_core/plugins/ArknightsUID/ArknightsUID/utils/resource/RESOURCE_PATH.py", line 2, in <module>
    from tkinter import CHAR

ModuleNotFoundError: No module named 'tkinter'
  File "/home/ubuntu/bot/gsuid_core1/gsuid_core/server.py", line 121, in load_plugins
    self.load_dir_plugins(path, True)
  File "/home/ubuntu/bot/gsuid_core1/gsuid_core/server.py", line 172, in load_dir_plugins
    importlib.import_module(f'{_p}')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/bot/gsuid_core1/gsuid_core/plugins/ArknightsUID/ArknightsUID/arknightsuid_resource/__init__.py", line 4, in <module>
    from gsuid_core.plugins.ArknightsUID.ArknightsUID.utils.resource.download_all_resource import (
  File "/home/ubuntu/bot/gsuid_core1/gsuid_core/plugins/ArknightsUID/ArknightsUID/utils/resource/download_all_resource.py", line 3, in <module>
    from .download_from_cos import download_all_file_from_cos
  File "/home/ubuntu/bot/gsuid_core1/gsuid_core/plugins/ArknightsUID/ArknightsUID/utils/resource/download_from_cos.py", line 3, in <module>
    from .RESOURCE_PATH import (
  File "/home/ubuntu/bot/gsuid_core1/gsuid_core/plugins/ArknightsUID/ArknightsUID/utils/resource/RESOURCE_PATH.py", line 2, in <module>
    from tkinter import CHAR
06-13 17:28:56 [WARNING] gsuid_core.server | 插件ArknightsUID加载失败
```

**Comment by baiqwerdvd** [comment]
修了
