### ISSUE TITLE
森空岛绑定报错

### ISSUE THREAD

**Issue by Kimorahsiki** [baiqwerdvd/ArknightsUID#6]
```
 10-30 14:57:13 [INFO] gsuid_core.handler | [Trigger] 消息 「skd添加cred ldhMG04mMsnZNLwcEPuY8ryu4g24****」 触发 「prefix」 类型触发器, 关键词: 「skd添加cred」
 10-30 14:57:13 [INFO] gsuid_core.handler | [Command] command=skd添加cred, text= ldhMG04mMsnZNLwcEPuY8ryu4g24****
 10-30 14:57:13 [INFO] ArknightsUID.utils.api.skd.request | {'code': 0, 'message': 'OK', 'timestamp': '1730271433', 'data': {'token': 'dbfa23414a942e7609ea4008eeeb7fb0'}}
 Task exception was never retrieved
future: <Task finished name='Task-114325' coro=<send_ark_skd_add_cred_msg() done, defined at C:\Users\Administrator\Desktop\gscore\gsuid_core\gsuid_core\sv.py:34> exception=AttributeError("'BaseArkApi' object has no attribute 'check_cred_valid'")>
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\gscore\gsuid_core\gsuid_core\sv.py", line 37, in wrapper
    result = await func(bot, event)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\gscore\gsuid_core\gsuid_core\plugins\ArknightsUID\ArknightsUID\arknightsuid_user\__init__.py", line 73, in send_ark_skd_add_cred_msg
    im = await deal_skd_cred(ev.bot_id, ev.text, ev.user_id)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\gscore\gsuid_core\gsuid_core\plugins\ArknightsUID\ArknightsUID\arknightsuid_user\deal_skd_cred.py", line 24, in deal_skd_cred
    check_cred = await ark_skd_api.check_cred_valid(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BaseArkApi' object has no attribute 'check_cred_valid'
```

**Comment by baiqwerdvd** [comment]
我懒得和角风控对抗，等之后有空了再说

**Comment by Kimorahsiki** [comment]
好的麻烦了哥

**Comment by WangMaoquan** [comment]
麻烦问一下怎么获取 cred 啊
